name: Test and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v ./

      - name: Get current date/time for tag
        id: get_time
        run: |
          echo "date=$(date -u +'%Y.%m.%d%H%M')" >> $GITHUB_OUTPUT

      - name: Create tag
        id: create_tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.get_time.outputs.date }}
          git push origin v${{ steps.get_time.outputs.date }}

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            const tag = `v${{ steps.get_time.outputs.date }}`
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              generate_release_notes: true
            }) 
